In [12]:
print("hello world")

hello world


In [13]:
import sys
sys.path.append('E:/PycharmProjects/TradingExam')

In [9]:
import optiver2023
env = optiver2023.make_env()
iter_test = env.iter_test()

ModuleNotFoundError: No module named 'optiver2023.competition'

In [1]:
r = range(0,8,1)
r

range(0, 8)

In [2]:
print(r)

range(0, 8)


In [3]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7


In [4]:
import numpy as np


In [5]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(a,b)

[1 2 3 4 5] [1 2 3 4 5]


In [6]:
c = a*b
print(c)

[ 1  4  9 16 25]


In [7]:
c.dtype

dtype('int64')

In [8]:
a.dtype

dtype('int64')

In [9]:
print(type(a), type(c))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [10]:
print(a.sum())

15


In [13]:
c = np.zeros()

In [17]:
h = np.arange(0,15,1)

In [18]:
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
h = h.reshape(5,3)
print(h)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [25]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])